name: Flashfood Bot

on:
  schedule:
    # 08:00–19:59 Detroit (12:00–23:59 UTC)
    - cron: "*/3 12-23 * * *"
    
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('flash/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build project
        run: mvn package -q
        working-directory: flash

      - name: Run bot
        working-directory: flash
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          FF_USERNAME: ${{ secrets.FF_USERNAME }}
          FF_PASSWORD: ${{ secrets.FF_PASSWORD }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: java -jar target/*.jar

      - name: Commit seen.txt
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add flash/seen.txt

          git commit --amend --no-edit || echo "No changes"

          git push --force
``
